Repository BinaryStudioAcademy/bsa-winter-2022-growup-mobile, pull requests merged in 2022-02, with the labels that each got.

#3 Splash screen added and app icon changed
  android/app/src/main/ic_launcher-playstore.png
  android/app/src/main/java/com/growupmobile/MainActivity.java
  android/app/src/main/res/drawable/launch_screen.png
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/ic_launcher_background.xml
  package.json
  src/App.tsx
  yarn.lock
Labels: enhancement

#6 feat(#8): add GitHub action to build&check android part
  .github/workflows/build-android.yml
  package.json
  src/screens/Home/index.tsx
Labels: enhancement

#2 #14 Setup redux
  src/App.tsx
  src/common/types/app/app-dispatch.ts
  src/common/types/app/index.ts
  src/common/types/app/root-state.ts
  src/hooks/index.ts
  src/hooks/use-app-dispatch.ts
  src/hooks/use-app-selector.ts
  src/store/actions.ts
  src/store/auth/actions.ts
  src/store/auth/common.ts
  src/store/auth/index.ts
  src/store/auth/slice.ts
  src/store/index.ts
  src/store/root-reducer.ts
  yarn.lock
Labels: enhancement, help wanted

#8 #24 Added theme, global components and styles
  src/App.tsx
  src/common/enums/index.ts
  src/common/enums/ui/app-color.ts
  src/common/enums/ui/button-mode.ts
  src/common/enums/ui/heading-level.ts
  src/common/enums/ui/index.ts
  src/common/enums/ui/text-appearance.ts
  src/components/heading/heading.tsx
  src/components/heading/index.ts
  src/components/heading/styles.ts
  src/components/index.ts
  src/components/input/index.ts
  src/components/input/input.tsx
  src/components/input/styles.ts
  src/components/main-button/index.ts
  src/components/main-button/main-button.tsx
  src/components/main-button/styles.ts
  src/components/text/index.ts
  src/components/text/styles.ts
  src/components/text/text.tsx
  src/screens/Home/index.tsx
  src/store/auth/slice.ts
  src/styles/fonts/font-config.ts
  src/styles/theme/index.ts
  src/styles/theme/theme.ts
  yarn.lock
Labels: enhancement

#12 feat(#12): add floating action button with menu on profile screen
  src/screens/profile/add-actions.ts
  src/screens/profile/profile.tsx
  src/screens/profile/styles.ts
  yarn.lock
Labels: enhancement

#14 #23: Fixed border radius for input
  src/components/input/input.tsx
  src/components/input/theme.ts
  src/screens/profile/profile.tsx
Labels: invalid

#15 GUM-24: add shared form using formik
  package.json
  src/components/form-field/form-field.tsx
  src/components/form-field/index.ts
  src/components/form-field/styles.ts
  src/components/form/form.tsx
  src/components/form/index.ts
  src/components/form/styles.ts
  src/components/index.ts
  yarn.lock
Labels: enhancement

#13 New/#21 fingerprint popup
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/growupmobile/MainApplication.java
  android/settings.gradle
  ios/growupmobile.xcodeproj/project.pbxproj
  ios/growupmobile.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/growupmobile.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/growupmobile/Info.plist
  package.json
  src/helpers/biometry/fingerprint/android/index.ts
  src/helpers/biometry/fingerprint/index.tsx
  src/helpers/biometry/fingerprint/ios/index.ts
  src/helpers/biometry/index.ts
  src/helpers/index.ts
  yarn.lock
Labels: enhancement

#22 #5 Create skills section
  src/common/enums/ui/app-color.ts
  src/common/enums/ui/index.ts
  src/common/enums/ui/tag-type.ts
  src/components/icons/icons.tsx
  src/components/index.ts
  src/components/tag/index.ts
  src/components/tag/styles.ts
  src/components/tag/tag.tsx
  src/screens/profile/components/index.ts
  src/screens/profile/components/skills-section/index.ts
  src/screens/profile/components/skills-section/skills-section.tsx
  src/screens/profile/components/skills-section/styles.ts
Labels: enhancement

#25 New/GUM 4 education card
  src/common/constants/date.ts
  src/common/constants/index.ts
  src/common/enums/ui/app-color.ts
  src/common/types/education/education.interface.ts
  src/common/types/education/index.ts
  src/common/types/index.ts
  src/components/icons/icons.tsx
  src/screens/profile/components/education-card/education-card.tsx
  src/screens/profile/components/education-card/index.ts
  src/screens/profile/components/education-card/styles.ts
  src/screens/profile/components/index.ts
Labels: enhancement

#26 New/GUM 28 mentee home screen
  src/common/enums/api/api-path.ts
  src/common/types/index.ts
  src/common/types/notification/index.ts
  src/common/types/notification/notification.interface.ts
  src/common/types/opportunity/index.ts
  src/common/types/opportunity/opportunity.interface.ts
  src/navigation/app/app-navigation.tsx
  src/navigation/index.tsx
  src/screens/create-skill/components/create-skill-form/create-skill-form.tsx
  src/screens/home/home.tsx
  src/screens/home/index.ts
  src/screens/index.ts
  src/screens/mentee-home/components/avatar/avatar.tsx
  src/screens/mentee-home/components/avatar/constants.ts
  src/screens/mentee-home/components/avatar/index.ts
  src/screens/mentee-home/components/header/header.tsx
  src/screens/mentee-home/components/header/index.ts
  src/screens/mentee-home/components/header/styles.ts
  src/screens/mentee-home/components/index.ts
  src/screens/mentee-home/components/minor-card/index.ts
  src/screens/mentee-home/components/minor-card/minor-card.tsx
  src/screens/mentee-home/components/minor-card/styles.ts
  src/screens/mentee-home/components/notification-card/index.ts
  src/screens/mentee-home/components/notification-card/notification-card.tsx
  src/screens/mentee-home/components/notification-card/styles.ts
  src/screens/mentee-home/components/notifications-section/index.ts
  src/screens/mentee-home/components/notifications-section/notifications.tsx
  src/screens/mentee-home/components/notifications-section/styles.ts
  src/screens/mentee-home/components/opportunities-section/index.ts
  src/screens/mentee-home/components/opportunities-section/opportunities-section.tsx
  src/screens/mentee-home/components/opportunities-section/styles.ts
  src/screens/mentee-home/components/opportunity-card/index.ts
  src/screens/mentee-home/components/opportunity-card/opportunity-card.tsx
  src/screens/mentee-home/components/opportunity-card/styles.ts
  src/screens/mentee-home/index.ts
  src/screens/mentee-home/mentee-home.tsx
  src/screens/mentee-home/styles.ts
  src/screens/profile/components/education-card/education-card.tsx
  src/services/index.ts
  src/services/notification-api/index.ts
  src/store/actions.ts
  src/store/notification/actions.ts
  src/store/notification/common.ts
  src/store/notification/index.ts
  src/store/notification/slice.ts
  src/store/root-reducer.ts
Labels: enhancement

#29 GUM-30: changed opportunity type, card design
  src/common/types/opportunity/opportunity.interface.ts
  src/components/icons/icons.tsx
  src/screens/mentee-home/components/opportunity-card/opportunity-card.tsx
  src/screens/mentee-home/components/opportunity-card/styles.ts
  src/screens/mentee-home/mentee-home.tsx
Labels: enhancement

#28 New/gum 29 location autocomplete
  .env.example
  package.json
  src/common/constants/env.ts
  src/common/constants/google-api.ts
  src/common/constants/index.ts
  src/common/enums/api/api-path.ts
  src/common/enums/ui/app-color.ts
  src/common/types/google-places/autocomplete-response.interface.ts
  src/common/types/google-places/index.ts
  src/common/types/google-places/place.interface.ts
  src/common/types/index.ts
  src/components/autocomplete-select/autocomplete-select.tsx
  src/components/autocomplete-select/index.ts
  src/components/autocomplete-select/styles.ts
  src/components/form/form-autocomplete-select/form-autocomplete-select.tsx
  src/components/form/form-autocomplete-select/index.ts
  src/components/form/form-google-location-select/form-google-location-select.tsx
  src/components/form/form-google-location-select/index.ts
  src/components/form/index.ts
  src/components/index.ts
  src/components/input/input.tsx
  src/hooks/index.ts
  src/hooks/use-debounced-timeout.ts
  src/screens/add-location/add-location.tsx
  src/screens/mentee-home/mentee-home.tsx
  src/screens/profile/components/education-card/education-card.tsx
  src/services/google-places-api/index.ts
  src/services/index.ts
  yarn.lock
Labels: enhancement

#31 New/GUM 32 token refresh
  src/services/http/index.ts
  src/store/auth/actions.ts
  src/store/auth/common.ts
  src/store/auth/slice.ts
Labels: enhancement

#7 GUM2: Create User profile basic info layout
  src/common/enums/ui/app-color.ts
  src/components/icons/icons.tsx
  src/navigation/index.tsx
  src/screens/profile/components/index.ts
  src/screens/profile/components/user-info/index.ts
  src/screens/profile/components/user-info/styles.ts
  src/screens/profile/components/user-info/user-info.tsx
Labels: enhancement

#9 GUM21: New/scaffold profile
  ios/Podfile
  src/common/constants/app.ts
  src/common/constants/index.ts
  src/screens/profile/components/index.ts
  src/screens/profile/components/navbar/constants.ts
  src/screens/profile/components/navbar/index.ts
  src/screens/profile/components/navbar/navbar.tsx
  src/screens/profile/components/navbar/styles.ts
  src/screens/profile/profile.tsx
  src/screens/profile/styles.ts
Labels: enhancement, help wanted

#27 GUM-3/career journey layout
  src/common/enums/app/date-format.ts
  src/common/enums/app/index.ts
  src/common/types/career/career.interface.ts
  src/common/types/career/index.ts
  src/common/types/index.ts
  src/navigation/index.tsx
  src/screens/profile/components/career-card/career-card.tsx
  src/screens/profile/components/career-card/index.ts
  src/screens/profile/components/career-card/styles.ts
  src/screens/profile/components/index.ts
  src/screens/profile/profile.tsx
Labels: enhancement

#32 Gum-32: Create AddOKR screen
  package.json
  src/common/enums/navigation/app-route.enum.ts
  src/common/types/navigation/app-stack-param.ts
  src/common/types/navigation/app-tabs-param.ts
  src/common/types/navigation/index.ts
  src/common/types/navigation/root-stack-param.ts
  src/common/types/okr/add-okr.interface.ts
  src/components/add-button/add-button.tsx
  src/components/add-button/index.ts
  src/components/add-button/styles.ts
  src/components/form/form-slider/form-slider.tsx
  src/components/form/form-slider/index.ts
  src/components/form/index.ts
  src/components/index.ts
  src/navigation/app-tabs/app-tabs-navigation.tsx
  src/navigation/app-tabs/index.ts
  src/navigation/app-tabs/styles.ts
  src/navigation/app/app-navigation.tsx
  src/navigation/app/index.ts
  src/navigation/index.tsx
  src/navigation/onboarding/onboarding-navigation.tsx
  src/screens/add-key-result/add-key-result.tsx
  src/screens/add-key-result/common.ts
  src/screens/add-key-result/index.ts
  src/screens/add-key-result/styles.ts
  src/screens/add-okr/add-okr.tsx
  src/screens/add-okr/common.ts
  src/screens/add-okr/index.ts
  src/screens/add-okr/styles.ts
  src/screens/index.ts
  src/screens/okr/add-actions.ts
  src/screens/okr/okr.tsx
  src/screens/okr/styles.ts
  src/screens/onboarding/components/index.ts
  src/screens/onboarding/components/step-content/education-content.tsx
  src/screens/onboarding/components/step-content/experience-content.tsx
  src/screens/onboarding/components/step-content/interesting-content.tsx
  src/services/index.ts
  src/services/okr-api/index.ts
  src/store/actions.ts
  src/store/okr/actions.ts
  src/store/okr/common.ts
  src/store/okr/index.ts
  src/store/okr/slice.ts
  src/store/root-reducer.ts
  src/validation-schemas/index.ts
  src/validation-schemas/okr/add-key-result.ts
  src/validation-schemas/okr/create-okr.ts
  src/validation-schemas/okr/index.ts
  yarn.lock
Labels: enhancement
