Repository BinaryStudioAcademy/bsa-winter-2022-growup-mobile, pull requests merged in 2022-03, with the labels that each got.

#34 GUM-35: Added navigation types
  src/common/types/navigation/index.ts
  src/common/types/navigation/params/app-stack-param.ts
  src/common/types/navigation/params/app-tabs-param.ts
  src/common/types/navigation/params/index.ts
  src/common/types/navigation/params/onboarding-stack-param.ts
  src/common/types/navigation/params/profile-stack-param.ts
  src/common/types/navigation/params/root-stack-param.ts
  src/common/types/navigation/props/index.ts
  src/common/types/navigation/props/root-navigation-props.ts
  src/hooks/index.ts
  src/hooks/use-app-navigation.ts
  src/navigation/app/app-navigation.tsx
  src/navigation/onboarding/onboarding-navigation.tsx
  src/navigation/profile/profile-navigation.tsx
  src/screens/add-education/add-education.tsx
  src/screens/add-experience/add-experience.tsx
  src/screens/add-key-result/add-key-result.tsx
  src/screens/add-language/add-language.tsx
  src/screens/add-location/add-location.tsx
  src/screens/add-okr/add-okr.tsx
  src/screens/create-skill/create-skill.tsx
  src/screens/login/login.tsx
  src/screens/mentee-home/components/header/header.tsx
  src/screens/okr/okr.tsx
  src/screens/onboarding/components/step-content/education-content.tsx
  src/screens/onboarding/components/step-content/experience-content.tsx
  src/screens/onboarding/components/step-content/interesting-content.tsx
  src/screens/onboarding/onboarding.tsx
  src/screens/profile/profile.tsx
  src/screens/register/register.tsx
Labels: enhancement, help wanted

#38 New/GUM 41 firebase push notifications
  .gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/growupmobile/MainApplication.java
  android/app/src/main/res/drawable/ic_notification.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  android/gradle.properties
  android/settings.gradle
  app.json
  ios/growupmobile.xcodeproj/project.pbxproj
  ios/growupmobile.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/growupmobile/AppDelegate.m
  ios/growupmobile/Info.plist
  package.json
  readme.md
  src/common/constants/index.ts
  src/common/constants/push-notifications.ts
  src/common/enums/index.ts
  src/common/enums/push-notifications/index.ts
  src/common/enums/push-notifications/push-notification-type.enum.ts
  src/push-handlers/abstraction.ts
  src/push-handlers/index.ts
  src/services/index.ts
  src/services/push-notifications-api/index.ts
  yarn.lock
Labels: enhancement

#36 New/GUM 36: add toast notifications
  package.json
  src/helpers/index.ts
  src/helpers/notifications/index.ts
  src/helpers/notifications/notifications.ts
  src/screens/login/components/login-form/login-form.tsx
  src/services/auth-api/index.ts
  src/services/notification-api/index.ts
  src/services/okr-api/index.ts
  src/services/skill-api/index.ts
  src/store/auth/actions.ts
  src/store/okr/actions.ts
  src/store/okr/slice.ts
  src/store/skill/actions.ts
  yarn.lock
Labels: enhancement

#41 Patch firebase push notifications
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  index.js
  src/App.tsx
  src/services/push-notifications-api/index.ts
Labels: enhancement

#42 New/GUM 44: add google services files to GH workflow
  .github/workflows/build-android.yml
Labels: enhancement

#45 GUM-46: fixed toasts + added where they were missing
  src/services/auth-api/index.ts
  src/services/career-api/index.ts
  src/services/google-places-api/index.ts
  src/services/notification-api/index.ts
  src/services/skill-api/index.ts
Labels: enhancement

#35 New/gum 22 biometric login
  android/app/build.gradle
  android/app/src/main/java/com/growupmobile/MainApplication.java
  android/settings.gradle
  ios/Podfile
  ios/growupmobile.xcodeproj/project.pbxproj
  package.json
  src/common/enums/app/secure-storage-key.ts
  src/common/types/auth/auth-response.interface.ts
  src/common/types/auth/index.ts
  src/helpers/biometry/biometric-credentials.ts
  src/helpers/biometry/fingerprint/android/index.ts
  src/helpers/biometry/fingerprint/index.tsx
  src/helpers/biometry/fingerprint/ios/index.ts
  src/helpers/biometry/index.ts
  src/helpers/index.ts
  src/screens/login/components/login-form/login-form.tsx
  src/screens/login/components/login-form/styles.ts
  src/screens/login/login.tsx
  src/screens/register/register.tsx
  src/services/auth-api/index.ts
  src/store/auth/actions.ts
  src/store/auth/common.ts
  yarn.lock
Labels: enhancement

#49 GUM-52: added 'add .env file' step to workflow
  .github/workflows/build-android.yml
Labels: enhancement

#47 GUM-50: Add logout
  src/components/icons/icons.tsx
  src/screens/profile/components/header/header.tsx
  src/screens/profile/components/header/index.ts
  src/screens/profile/components/header/styles.ts
  src/screens/profile/components/index.ts
  src/screens/profile/profile.tsx
  src/screens/profile/styles.ts
  src/store/auth/actions.ts
  src/store/auth/slice.ts
Labels: enhancement

#53 Fix/GUM 58 login env
  .github/workflows/build-android.yml
Labels: enhancement

#50 New/GUM 48 opportunity details
  src/common/constants/home-screen.ts
  src/common/constants/index.ts
  src/common/enums/navigation/app-route.enum.ts
  src/common/types/navigation/params/app-stack-param.ts
  src/common/types/opportunity/full-opportunity.interface.ts
  src/common/types/opportunity/index.ts
  src/common/types/opportunity/opportunity.interface.ts
  src/components/opportunity-card/opportunity-card.tsx
  src/components/opportunity-card/styles.ts
  src/hooks/index.ts
  src/hooks/use-stack-screen-options.ts
  src/navigation/app/app-navigation.tsx
  src/navigation/app/styles.ts
  src/navigation/onboarding/onboarding-navigation.tsx
  src/screens/index.ts
  src/screens/mentee-home/mentee-home.tsx
  src/screens/opportunities/opportunities.tsx
  src/screens/opportunity-details/index.ts
  src/screens/opportunity-details/opportunity-details.tsx
  src/screens/opportunity-details/styles.ts
  src/services/opportunities-api/index.ts
  src/store/opportunities/actions.ts
  src/store/opportunities/common.ts
  src/store/opportunities/slice.ts
Labels: enhancement

#56 Fix tags TypeError
  src/common/types/index.ts
  src/common/types/opportunity/opportunity.interface.ts
  src/common/types/tag/index.ts
  src/common/types/tag/tag.interface.ts
  src/components/opportunity-card/opportunity-card.tsx
Labels: enhancement

#55 New/GUM 60 registration redirect
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  ios/Podfile
  ios/growupmobile.xcodeproj/project.pbxproj
  ios/growupmobile/AppDelegate.m
  ios/growupmobile/Info.plist
  src/App.tsx
  src/common/constants/index.ts
  src/common/constants/linking.ts
  src/common/enums/navigation/auth-route.enum.ts
  src/common/types/navigation/params/root-stack-param.ts
  src/components/index.ts
  src/components/navigation-container/index.ts
  src/components/navigation-container/navigation-container.tsx
  src/navigation/index.tsx
  src/screens/complete-registration/complete-registration.tsx
  src/screens/complete-registration/index.ts
  src/screens/index.ts
Labels: enhancement

#57 New/GUM 54 quiz diagram
  package.json
  src/common/constants/app.ts
  src/common/constants/index.ts
  src/common/constants/quiz.ts
  src/common/constants/radar-chart.ts
  src/common/enums/ui/app-color-dark.ts
  src/common/enums/ui/app-color-light.ts
  src/common/types/geometry/index.ts
  src/common/types/geometry/point.interface.ts
  src/common/types/geometry/polar-point.interface.ts
  src/common/types/index.ts
  src/components/index.ts
  src/components/radar-chart/index.ts
  src/components/radar-chart/radar-chart.tsx
  src/helpers/geometry/angles.ts
  src/helpers/geometry/coordinates.ts
  src/helpers/geometry/figures.ts
  src/helpers/geometry/index.ts
  src/helpers/index.ts
  src/screens/profile/components/index.ts
  src/screens/profile/components/quiz-results/index.ts
  src/screens/profile/components/quiz-results/quiz-results.tsx
  src/screens/profile/profile.tsx
  src/services/career-api/index.ts
  src/services/quiz-api/index.ts
  src/store/quiz/slice.ts
  yarn.lock
Labels: enhancement

#58 Patch/GUM 57 error handling
  src/common/types/http/http-error-options.ts
  src/common/types/http/http-options.ts
  src/common/types/http/index.ts
  src/components/form/form-google-location-select/form-google-location-select.tsx
  src/services/auth-api/index.ts
  src/services/career-api/index.ts
  src/services/google-places-api/index.ts
  src/services/http/index.ts
  src/services/notification-api/index.ts
  src/services/okr-api/index.ts
  src/services/opportunities-api/index.ts
  src/services/quiz-api/index.ts
  src/services/skill-api/index.ts
  src/store/auth/actions.ts
Labels: enhancement, resolve conflicts

#61 Fix/GUM 62 changed auth form layout
  src/components/auth-screen/auth-screen.tsx
  src/components/auth-screen/styles.ts
  src/components/index.ts
  src/components/logo/index.ts
  src/components/logo/logo.tsx
  src/components/logo/styles.ts
  src/hooks/use-asset.ts
  src/screens/login/components/login-form/login-form.tsx
  src/screens/login/components/login-form/styles.ts
  src/screens/register/components/register-form/register-form.tsx
  src/screens/register/components/register-form/styles.ts
Labels: enhancement

#65 Fix/GUM 69 relinked webview and canvas
  android/app/src/main/java/com/growupmobile/MainApplication.java
  android/settings.gradle
  ios/Podfile
Labels: enhancement

#60 Fix/GUM 64 add placeholders on empty list
  src/components/empty-list-message/empty-list-message.tsx
  src/components/empty-list-message/index.ts
  src/components/empty-list-message/styles.ts
  src/components/index.ts
  src/screens/mentee-home/mentee-home.tsx
  src/screens/okr/okr.tsx
  src/screens/opportunities/opportunities.tsx
  src/screens/profile/profile.tsx
Labels: enhancement

#66 Fix/fixed create skill form style hook
  src/components/form/form-input/form-input.tsx
  src/screens/create-skill/common.ts
  src/screens/create-skill/components/create-skill-form/create-skill-form.tsx
Labels: enhancement

#67 Fix/GUM 11 create skill api call
  src/common/enums/skill/skill-type.ts
  src/common/types/skill/create-skill.interface.ts
  src/screens/create-skill/common.ts
  src/screens/create-skill/components/create-skill-form/create-skill-form.tsx
  src/services/skill-api/index.ts
  src/validation-schemas/skill/create-skill.ts
Labels: enhancement

#64 Fix/GUM 61 added input strings trimming
  src/components/form/form-input/form-input.tsx
  src/components/form/form-password-input/form-password-input.tsx
  src/validation-schemas/auth/login.ts
  src/validation-schemas/auth/register.ts
  src/validation-schemas/education/add-education.ts
  src/validation-schemas/experience/add-experience.ts
  src/validation-schemas/language/add-language.ts
  src/validation-schemas/location/add-location.ts
  src/validation-schemas/okr/add-key-result.ts
  src/validation-schemas/okr/create-okr.ts
  src/validation-schemas/skill/create-skill.ts
  src/validation-schemas/user/user-info.ts
Labels: enhancement

#62 GUM-56: Connect onboarding to backend
  src/common/enums/api/api-path.ts
  src/common/types/career/add-career.interface.ts
  src/common/types/index.ts
  src/common/types/language/add-language.interface.ts
  src/common/types/language/index.ts
  src/common/types/language/language.interface.ts
  src/common/types/navigation/params/onboarding-stack-param.ts
  src/common/types/navigation/params/profile-stack-param.ts
  src/common/types/onboarding/index.ts
  src/common/types/onboarding/onboarding.interface.ts
  src/common/types/user/index.ts
  src/common/types/user/user-info.interface.ts
  src/common/types/user/user.interface.ts
  src/components/avatar-picker/index.ts
  src/components/career-card/career-card.tsx
  src/components/career-card/index.ts
  src/components/career-card/styles.ts
  src/components/education-card/education-card.tsx
  src/components/education-card/index.ts
  src/components/education-card/styles.ts
  src/components/form/form-avatar-picker/form-avatar-picker.tsx
  src/components/form/form-avatar-picker/index.ts
  src/components/form/form-image-picker/form-image-picker.tsx
  src/components/form/form-image-picker/index.ts
  src/components/form/index.ts
  src/components/image-picker/image-picker.tsx
  src/components/image-picker/index.ts
  src/components/image-picker/styles.ts
  src/components/index.ts
  src/components/language-card/index.ts
  src/components/language-card/language-card.tsx
  src/components/language-card/styles.ts
  src/navigation/app/app-navigation.tsx
  src/screens/add-experience/add-experience.tsx
  src/screens/add-language/add-language.tsx
  src/screens/add-language/common.ts
  src/screens/add-language/styles.ts
  src/screens/onboarding/components/step-content/experience-content.tsx
  src/screens/onboarding/components/step-content/interesting-content.tsx
  src/screens/onboarding/components/step-content/styles.ts
  src/screens/onboarding/components/step-content/user-content.tsx
  src/screens/onboarding/onboarding.tsx
  src/screens/profile/components/index.ts
  src/screens/profile/profile.tsx
  src/services/index.ts
  src/services/language-api/index.ts
  src/services/onboarding-api/index.ts
  src/store/actions.ts
  src/store/auth/slice.ts
  src/store/language/actions.ts
  src/store/language/common.ts
  src/store/language/index.ts
  src/store/language/slice.ts
  src/store/onboarding/actions.ts
  src/store/onboarding/common.ts
  src/store/onboarding/index.ts
  src/store/onboarding/slice.ts
  src/store/root-reducer.ts
  src/validation-schemas/language/add-language.ts
Labels: enhancement

#72 New/GUM 68 auth spinner
  src/screens/login/components/login-form/login-form.tsx
  src/screens/register/components/register-form/register-form.tsx
  src/store/auth/slice.ts
Labels: enhancement

#43 GUM-39: add education feature connect to backend
  src/common/enums/api/api-path.ts
  src/common/enums/navigation/profile-route.enum.ts
  src/common/types/education/add-education.interface.ts
  src/common/types/education/education.interface.ts
  src/common/types/education/index.ts
  src/common/types/navigation/params/profile-stack-param.ts
  src/navigation/profile/profile-navigation.tsx
  src/screens/add-education/add-education.tsx
  src/screens/add-education/common.ts
  src/screens/profile/profile.tsx
  src/services/education-api/index.ts
  src/services/index.ts
  src/store/actions.ts
  src/store/education/actions.ts
  src/store/education/common.ts
  src/store/education/index.ts
  src/store/education/slice.ts
  src/store/root-reducer.ts
  src/validation-schemas/education/add-education.ts
Labels: enhancement

#75 GUM-73: Fixed app crash on profile
  src/screens/profile/profile.tsx
Labels: bug

#74 GUM-66: Fixed date input error styles and validation bugs
  src/components/form/form-date/form-date.tsx
  src/components/form/styles.ts
  src/screens/profile/add-actions.ts
Labels: bug

#73 New/GUM 72 add all real user info
  src/components/avatar/avatar.tsx
  src/screens/mentee-home/mentee-home.tsx
  src/screens/profile/components/user-info/user-info.tsx
  src/screens/profile/profile.tsx
Labels: enhancement

#77 GUM-66: Refactored code in date inputs
  src/common/constants/date.ts
  src/components/form/form-date/form-date.tsx
Labels: enhancement
