Repository BinaryStudioAcademy/bsa-winter-2022-growup-mobile, pull requests merged in 2022-04, with the labels that each got.

#80 GUM-75: Fixed app navigation, added language content, fixed quiz
  src/common/enums/navigation/onboarding-route.enum.ts
  src/common/enums/navigation/profile-route.enum.ts
  src/common/types/navigation/params/app-stack-param.ts
  src/common/types/navigation/params/app-tabs-param.ts
  src/common/types/navigation/params/onboarding-stack-param.ts
  src/common/types/navigation/params/profile-stack-param.ts
  src/navigation/profile/profile-navigation.tsx
  src/screens/add-education/add-education.tsx
  src/screens/add-experience/add-experience.tsx
  src/screens/mentee-home/components/header/header.tsx
  src/screens/onboarding/components/step-content/experience-content.tsx
  src/screens/profile/add-actions.ts
  src/screens/profile/profile.tsx
  src/screens/quiz/quiz.tsx
  src/store/quiz/slice.ts
Labels: bug, enhancement

#82 GUM-77: Fixed scroll on home and opportunity screen and text
  src/navigation/app/app-navigation.tsx
  src/screens/create-skill/components/create-skill-form/create-skill-form.tsx
  src/screens/mentee-home/mentee-home.tsx
  src/screens/opportunities/opportunities.tsx
  src/screens/profile/add-actions.ts
  src/screens/profile/profile.tsx
Labels: bug

#78 GUM-74: Add education features on onboarding
  src/common/types/navigation/params/onboarding-stack-param.ts
  src/components/education-card/education-card.tsx
  src/screens/onboarding/components/step-content/education-content.tsx
Labels: enhancement

#83 Patch/GUM 18 remove firstName and lastName from add user form
  src/common/types/user/add-user-payload.interface.ts
  src/screens/add-user/add-user.tsx
  src/screens/add-user/common.ts
  src/validation-schemas/user/add-user.ts
Labels: enhancement

#85 Patch/GUM 79 added initials to avatar
  src/components/avatar/avatar.tsx
  src/components/avatar/constants.ts
  src/screens/admin-home/admin-home.tsx
  src/screens/admin-home/styles.ts
  src/screens/mentee-home/components/avatar/avatar.tsx
  src/screens/mentee-home/components/avatar/constants.ts
  src/screens/mentee-home/components/avatar/index.ts
  src/screens/mentee-home/components/header/header.tsx
  src/screens/mentee-home/components/index.ts
  src/screens/mentee-home/mentee-home.tsx
  src/screens/opportunity-details/opportunity-details.tsx
  src/screens/profile/components/user-info/user-info.tsx
Labels: enhancement

#84 GUM-78: Fixed quiz results and added more info
  src/common/enums/index.ts
  src/common/enums/quiz/index.ts
  src/common/enums/quiz/quiz-category-names.enum.ts
  src/common/types/onboarding/onboarding.interface.ts
  src/common/types/quiz/quiz-category.interface.ts
  src/common/types/user/index.ts
  src/common/types/user/user-domain.interface.ts
  src/common/types/user/user-info.interface.ts
  src/common/types/user/user-level.interface.ts
  src/common/types/user/user.interface.ts
  src/navigation/app-tabs/app-tabs-navigation.tsx
  src/screens/onboarding/components/step-content/common.ts
  src/screens/onboarding/components/step-content/user-content.tsx
  src/screens/profile/components/quiz-results/common.ts
  src/screens/profile/components/quiz-results/quiz-results.tsx
  src/screens/profile/components/quiz-results/styles.ts
  src/screens/profile/components/user-info/user-info.tsx
  src/store/onboarding/slice.ts
  src/store/quiz/actions.ts
  src/store/quiz/slice.ts
  src/validation-schemas/user/user-info.ts
Labels: bug, enhancement

#71 New/GUM 70 pull to refresh
  src/screens/mentee-home/mentee-home.tsx
  src/screens/opportunities/components/index.ts
  src/screens/opportunities/components/list/index.ts
  src/screens/opportunities/components/list/list.tsx
  src/screens/opportunities/opportunities.tsx
  src/screens/profile/profile.tsx
  src/store/education/slice.ts
  src/store/experience/slice.ts
  src/store/language/slice.ts
Labels: enhancement

#91 Hotfix/GUM fix oppotrunities screen
  src/screens/opportunities/opportunities.tsx
Labels: enhancement

#89 GUM-88: Fixed onboarding data bug
  src/common/types/onboarding/onboarding.interface.ts
  src/screens/profile/components/user-info/user-info.tsx
  src/services/education-api/index.ts
  src/store/onboarding/slice.ts
Labels: bug

#90 Fix/gum 80 add skill
  src/common/types/skill/skill.interface.ts
  src/components/index.ts
  src/components/skill-card/index.ts
  src/components/skill-card/skill-card.tsx
  src/components/skill-card/styles.ts
  src/screens/create-skill/components/create-skill-form/create-skill-form.tsx
  src/screens/create-skill/styles.ts
  src/screens/profile/profile.tsx
  src/services/skill-api/index.ts
  src/store/skill/actions.ts
  src/store/skill/common.ts
  src/store/skill/slice.ts
Labels: bug, enhancement

#92 GUM: remove notification mark read request
  src/services/notification-api/index.ts
Labels: enhancement
